services:
  postgres:
    image: 'postgres:16'
    container_name: "kontur-link-postgres"
    environment:
      - 'POSTGRES_DB=link_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5555:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"

  redis:
    image: 'redis:7'
    container_name: "kontur-link-redis"
    restart: always
    ports:
      - '6666:6379'
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5