server:
  port: 8080

spring:
  application:
    name: link-service

  datasource:
    url: jdbc:postgresql://localhost:5555/link_db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
